---
title: "High-throughput testing of drugs"
output: html_document
date: '2023-04-27'
---

```{r setup, include=FALSE}
mylib = 'C:\\Users\\zuendj\\Documents\\R4Libs'
mydir = "C:/Users/zuendj/Desktop/03_data R/wp1/output/final"
myfunctions = "C:/Users/zuendj/Desktop/03_data R/divcom_functions/R"
.libPaths(mylib)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(echo = TRUE, warning = FALSE, message = FALSE)
# devtools::install_github("tidyverse/tidyverse")
# library(phyloseq)
# library(tidyverse)
# library(openxlsx)
# library(microViz)
# library(rstatix)
# library(ggpubr)
# library(plyr)
# library(ggpmisc)
```

```{r}
#load required functions from fconstancias: https://zenodo.org/records/6473394
setwd(myfunctions)
source("./phyloseq_taxa_tests.R") 
source("./phyloseq_normalisation.R") 
source("./phyloseq_alpha.R") 
source("./phyloseq_beta.R") 
source("./phyloseq_heatmap.R")
source("./phyloseq_taxa_tests.R")
# source("./functions.R")

#function for getting metadata file
sample.data.frame <- function(ps) {
  return(as(phyloseq::sample_data(ps), "data.frame"))}
```

```{r}
HTP <-readRDS("P:/Shared_documents/Former members/Serafina Plüss/13_High-throughput_JANINA_part2/03_sequencing_data/dada2/phyloseq.RDS")
```

### Get and update metadata file
```{r, echo=FALSE}

HTP%>%
  physeq_add_metadata(physeq = .,
                      metadata = "P:/Shared_documents/Former members/Serafina Plüss/13_High-throughput_JANINA_part2/03_sequencing_data/mapping_file_updated.xlsx" %>%
                        readxl::read_xlsx(),
                      sample_column = "sample_name") -> HTP




meta_htp<-sample.data.frame(HTP)

meta_htp$donor <- recode_factor(meta_htp$donor, "FDS" = "WPL")



meta_htp$inoculation<-factor(meta_htp$inoculation, levels = c("0.1", "0.01", "feces"))
meta_htp$incubation<-factor(meta_htp$incubation, levels = c("24h", "48h", "feces"))

sample_data(HTP)<-meta_htp
```

```{r}
ps_strain_filt <- HTP

###filter 1
# threshold in %
threshold = 0.1

# filter per sample to remove all ASV lower in abundance than threshold (%)
otu_table(ps_strain_filt) <- otu_table(ps_strain_filt) %>%
  as.data.frame() %>%
  dplyr:: mutate(across(everything(), ~ ifelse(. <= sum(.) * (threshold/100), 0, .))) %>% otu_table(., taxa_are_rows = TRUE)

# remove all ASVs that are not present in any sample
ps_strain_filt <- ps_strain_filt %>%
  filter_taxa(function(x) sum(x > 0) > 0, TRUE)


ps_strain_filt%>% 
  phyloseq_check_lib_size(data_color = "experiment",
                          data_facet = NULL,
                          nreads_display = 1556,
                        first_n = nsamples(HTP)) -> lib

```



### Rarefaction
it is recommended to do rarefaction for alpha and beta diversity analysis

```{r}
ps_strain_filt %>%
  rarefy_even_depth(rngseed = 123,
                    sample.size = 4129
                    # sample.size = 5000
                    )%>%
  subset_samples(!donor %in% "WDR")-> HTP_rare
```
##Alpha diversity

```{r}
# unload("mia")
#alpha diversity
HTP_rare%>%
  phyloseq_alphas(phylo = TRUE) -> alphas
```


```{r}
x<-paste("OBSERVED_alpha diversity.jpg")
title<-paste("Alpha diversity")

alphas%>%
  subset(experiment %in% c("HTP"))%>%
  subset(treatment %in% c( "control",
                           "DMSO",
                          "ciprofloxacin",
                          "omeprazole",
                          "5-FU"))->alphas_drugs

alphas_drugs$treatment<-factor(alphas_drugs$treatment, levels=c("control", "DMSO","omeprazole",
                          "ciprofloxacin","5-FU"))

alphas_drugs$sample_type <-factor(alphas_drugs$sample_type, levels=c("feces", "culture"))

alphas_drugs%>%
  wilcox_test(observed ~ treatment, ref.group = "control")

alphas_drugs%>%
  mutate(vehicle ="water")%>%
  mutate(vehicle = ifelse(treatment %in% c("DMSO", "omeprazole"), "DMSO", vehicle))%>%
  ggplot(aes(x = treatment,
             y = observed)) +
  geom_boxplot(aes(group=treatment), outlier.shape = NA) +
  geom_point(aes(colour =donor, group=treatment), position= position_jitterdodge(0.3), alpha=0.75,   size = 3)+
  ylab("Observed ASVs") + xlab(NULL) +
  theme(axis.text.y= element_text(size = 20), 
            axis.title.y = element_text(size=20), 
            axis.title.x = element_text(size=20),
            axis.text.x = element_text(size=20, angle=90, vjust=0.2, hjust=1),
            legend.text = element_text(size = 20),
            legend.title = element_text(size= 20),
            plot.title = element_text(size=20),
           strip.text.x = element_blank(), 
        panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA), axis.ticks.x=element_blank())+
  ggtitle(title)+
  scale_x_discrete(labels = c('control' = expression(H[2]*O), 'omeprazole' = 'Omeprazole', 'ciprofloxacin' = 'Ciprofloxacin', "5-FU"="5-FU"))+
  labs(colour="Donor")+
  facet_grid(cols=vars(vehicle), scales="free", space="free")->alpha

# show(alpha)
show(alpha+ theme(legend.position = "none"))

ggsave(filename = "alpha_drugs_dmso..jpeg",
       path = "C:/Users/zuendj/Desktop/03_data R/wp1/output/final",
       width =8.5,
       height = 14,
       units = c("cm"))

51.7/14*8.5
```

```{r}
x<-paste("OBSERVED_alpha diversity.jpg")
title<-paste("Alpha diversity")

alphas%>%
  subset(experiment %in% c("HTP"))%>%
  # subset(treatment %in% c("control", "DMSO"))->alphas_drugs
  subset(treatment %in% c( "control",
                          "DMSO"))->alphas_drugs

alphas_drugs$treatment<-factor(alphas_drugs$treatment, levels=c("control", "DMSO"))

alphas_drugs$sample_type <-factor(alphas_drugs$sample_type, levels=c("feces", "culture"))


alphas_drugs%>%
  ggplot(aes(x = treatment,
             y = observed)) +
  geom_boxplot(aes(group=treatment), outlier.shape = NA) +
  geom_point(aes(colour =donor, group=treatment), position= position_jitterdodge(0.3), alpha=0.75,   size = 3)+
  ylab("Observed ASVs") + xlab(NULL) +
  theme(axis.text.y= element_text(size = 20), 
            axis.title.y = element_text(size=20), 
            axis.title.x = element_text(size=20),
            axis.text.x = element_text(size=20, angle=90, vjust=0.2, hjust=1),
            legend.text = element_text(size = 20),
            legend.title = element_text(size= 20),
            plot.title = element_text(size=20),
          strip.text.x = element_blank(), panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA))+
  ggtitle(title)+
  scale_x_discrete(labels = c('control' = expression(Control~(H[2]*O)), 'omeprazole' = 'Omeprazole', 'ciprofloxacin' = 'Ciprofloxacin', "5-FU"="5-FU"))+
  labs(colour="Donor")->alpha

show(alpha)
# show(alpha+ theme(legend.position = "none"))

ggsave(filename = "alpha_dmso.jpeg",
       path = "C:/Users/zuendj/Desktop/03_data R/wp1/output/final",
       width = 14,
       height = 17,
       units = c("cm"))


# alpha %>%
#   ggpubr::get_legend() %>%
#   ggpubr::as_ggplot() + theme_classic() -> vulcano_legend
#  
#  
#  ggsave(filename = "alpha_legend_drugs.jpeg",
#        path = "C:/Users/zuendj/Desktop/03_data R/wp1/follow_up_2/output_seq",
#        width = 17,
#        height = 14,
#        units = c("cm"))

51.7/14*14.7
```

##Barplots

### Compositional bar plots for each donor

```{r}
# phylo_C@otu_table
# 
# phylo_C@tax_table


noNA = !is.na(tax_table(HTP_rare)[,"Genus"]) & !is.na(tax_table(HTP_rare)[,"Species"])
tax_table(HTP_rare)[noNA][,"Species"] = paste(tax_table(HTP_rare)[noNA][,"Genus"], tax_table(HTP_rare)[noNA][,"Species"])

HTP_rare%>%
  tax_fix()->HTP_rare
  
noNA = !is.na(tax_table(HTP)[,"Genus"]) & !is.na(tax_table(HTP)[,"Species"])
tax_table(HTP)[noNA][,"Species"] = paste(tax_table(HTP)[noNA][,"Genus"], tax_table(HTP)[noNA][,"Species"])

HTP%>%
  tax_fix()->HTP
  
# tax_fix_interactive(fix)
```

##Bar plots: Drug
```{r}
HTP_rare%>%
  subset_samples(experiment %in% "HTP")%>%
  subset_samples(treatment %in% c("feces","control",
                          "DMSO",
                          "metformin",
                          "ciprofloxacin",
                          "omeprazole",
                          "5-FU"))-> HTP_drugs


meta_htp<-sample.data.frame(HTP_drugs)
meta_htp$treatment<-factor(meta_htp$treatment, levels = c("feces","control",
                          "DMSO",
                          "metformin",
                          "ciprofloxacin",
                          "omeprazole",
                          "5-FU"))
sample_data(HTP_drugs)<-meta_htp

HTP_drugs%>%
  ps_arrange(treatment)%>%
  microViz::comp_barplot(
    tax_level = "Family",
    label = "treatment",
    n_taxa = 19,
    bar_width = 0.9,
    sample_order = "default",
    tax_transform_for_plot = "compositional") +
    ylab("Composition") + xlab( "")-> p_hist
# +scale_x_discrete(labels = c('feces' = 'feces', '7C' = '6C+Muc', '3C+Muc' = '3C+Muc', "GMM like"="GMM like", "BHI like", "7C-Muc"="6C", "3C"="3C", "H2O"=expression(paste(H[2]*O)), "Glc"="glucose")) -> p_hist

p_hist + facet_grid(~donor, scales = "free_x", space = "free_x", drop = TRUE)+
  theme(axis.text.x = element_text(size=20, angle=90, vjust=0.2, hjust=1, margin=margin(-8,0,0,0)),
        axis.ticks.x = element_blank(),strip.text = element_text(size  = 20),
          axis.text.y= element_text(size = 20), 
        axis.title.y = element_text(size=20), 
        axis.title.x = element_text(size=20),
        legend.text = element_text(size = 20, vjust=1, hjust=0),
        legend.title = element_text(size= 20),
        plot.title = element_text(size=20), panel.spacing = unit(0.2, "cm")) + scale_y_continuous(breaks=c(0.25, 0.5, 0.75))+ ggtitle("Taxonomic distribution and ASV representation in cultures and feces")-> p_hist

show(p_hist+ theme(legend.position = "none"))


ggsave(filename = "drugs_bar.jpeg",
       path = "C:/Users/zuendj/Desktop/03_data R/wp1/follow_up_2/output_seq",
       width = 50,
       height = 20,
       units = c("cm"))
```

##Beta-div: drugs

```{r}
 # library(plyr)
dist = "bray"
# dist = "jaccard"
ord_meths = c("PCoA")

HTP_drugs%>%
  subset_samples(treatment %in% c("control", "DMSO" ))-> HTP_dsmo


plist = llply(as.list(ord_meths), function(i, HTP_dsmo, dist){
        ordi = ordinate(HTP_dsmo, method=i, distance=dist)
        plot_ordination(physeq = HTP_dsmo, 
                        ordination = ordi,
                        color = "donor", 
                        title = "PCoA Bray-Curtis")},
        HTP_dsmo, 
        dist)


names(plist) <- ord_meths

pdataframe = ldply(plist, function(x){
    df = x$data[, 1:2]
    colnames(df) = c("Axis_1", "Axis_2")
    return(cbind(df, x$data))})


names(pdataframe)[1] = "method"


  
  x<-paste("Bray Curtis dissimilarity.jpg")
  title<-paste("Bray-Curtis dissimilarity")
  

  pdataframe%>%
    ggplot(aes(Axis_1, Axis_2))+ 
    scale_shape_manual(values = c(19, 17, 2, 3, 4, 0, 5), labels=c(expression(Control~(H[2]*O)), "DMSO"))+
    scale_fill_manual(values=c("darkgoldenrod2", "cyan4"), labels=c(expression(Control~(H[2]*O)), "DMSO"))+
    stat_ellipse( aes(group=treatment, fill=treatment),geom = "polygon", lwd=0.01, alpha=0.2 )+
    geom_point(aes(fill=donor, shape=treatment, colour= donor),   fill="grey", alpha=1, size=4.5, stroke=0.2)+
    ggtitle(title)+
    theme(strip.text = element_text(size  = 20),
          axis.text.y= element_text(size = 20), 
        axis.title.y = element_text(size=20), 
        axis.title.x = element_text(size=20),
        axis.text.x = element_text(size=20),
        legend.text = element_text(size = 20, vjust=1, hjust=0),
        legend.title = element_text(size= 20),
        plot.title = element_text(size=20), panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA))+
   xlab("PCoA1") + ylab("PCoA2")+labs(shape="Condition", colour="Donor", fill="Condition")->p
  
  # show(p+ theme(legend.position = "none"))
  p
  
  ggsave(filename = "Beta_diversity_drugs.jpeg",
       path = "C:/Users/zuendj/Desktop/03_data R/wp1/output/final",
       width = 18,
       height = 14,
       units = c("cm"))

   # p %>%
#   ggpubr::get_legend() %>%
#   ggpubr::as_ggplot() + theme_classic() -> vulcano_legend
# 
# ggsave(filename = "Beta_diversity_legend_proteins.jpeg",
#        path = "C:/Users/zuendj/Desktop/03_data R/wp1/follow_up_2/output_seq",
#        width = 14,
#        height = 18,
#        units = c("cm"))
#   
     63.5/17*18
```


## Distance plots of pairwise comparisons

```{r}
# unload("dplyr")
# library(tidyverse)
#  library(dplyr)
HTP_rare %>%
  subset_samples(experiment %in% c("HTP"))%>%
  subset_samples(treatment %in% c("control",
                          "ciprofloxacin",
                           "omeprazole",
                          "5-FU"))->HTP_drugs
HTP_drugs %>%
  phyloseq::distance(method = "bray") -> bc

HTP_drugs %>%
  ordinate(method = "PCoA",
           distance = bc) -> ord

HTP_drugs %>%
  phyloseq_distance_boxplot(p = ., # phyloseq object
                            dist = bc, # distance matrix
                            d = "treatment") -> out # column in metadata for comparaisons


out$plot

setNames(as.data.frame(out$matrix),c("sample_name", "sample_name_comp", "value", "condition_comp", "comparison")) -> distances


distances%>%
  subset(comparison %in% c("control"))-> distances

means<-setNames(aggregate(distances$value, by=list(distances$condition_comp), FUN=mean), c("condition_comp", "mean_value"))

joined<-left_join(distances, sample.data.frame(HTP_drugs))
joined_2<-left_join(joined, means)



title="Distances between feces and cultures"

unique(joined_2$condition_comp)



sample.data.frame(HTP_drugs)[,c(1,3)]%>%
  subset(sample_name %in% c("JZ-009","JZ-017", "JZ-025", "JZ-033", "JZ-041", "JZ-049", "JZ-057", "JZ-065"))%>%
  setNames(c("sample_name_comp", "donor_name_comp"))->donor_comp

joined_3<-left_join(joined_2, donor_comp)


for (i in 1:nrow(joined_3)){
  if (joined_3[i,c("donor")] == joined_3[i,c("donor_name_comp")]){joined_3[i,c("match")]= "true"}
}



joined_3%>%
  subset(match %in% "true")->sub


sub$condition_comp<-factor(sub$condition_comp, levels= c("control",  "omeprazole", "ciprofloxacin", "5-FU"))

sub%>%
  # mutate(condition_comp = fct_reorder(condition_comp, sub$mean_value))%>%
  ggplot(aes(y=value, x=condition_comp))+
  # scale_color_manual(values=c( "coral4", 'black'))+
  geom_boxplot(aes(group=condition_comp),  outlier.shape =  NA)+
  geom_jitter(aes(group=condition_comp, colour=donor), width= 0.2, alpha=0.75, size=3)+
  theme(axis.text.y= element_text(size = 20), 
        axis.title.x = element_blank(), 
        axis.title.y = element_text(size=20),
        axis.text.x = element_text(size = 20, angle=90, vjust=0.2, hjust=1),
        legend.text = element_text(size = 20),
        legend.title = element_text(size= 20),
        plot.title = element_text(size=20),
        strip.text.x = element_blank(),
        axis.ticks.x = element_blank(), panel.background = element_rect(fill="white"),
        panel.border=element_rect(fill=NA)
        )+
  # stat_pvalue_manual(stat.test, hide.ns = T, label = "p.adj.signif")+
  scale_x_discrete(labels = c('ciprofloxacin' = 'Ciprofloxacin', 'omeprazole' = 'Omeprazole'))+
  ggtitle("Distance to control")+
  ylab("Bray-Curtis distance")+
  labs(colour="Donor")->p

show(p+ theme(legend.position = "none"))
  
  ggsave(filename = "Beta_diversity_dist_drugs.jpeg",
       path = "C:/Users/zuendj/Desktop/03_data R/wp1/output/final",
       width = 7.5,
       height = 14,
       units = c("cm"))
# 
 p %>%
ggpubr::get_legend() %>%
ggpubr::as_ggplot() + theme_classic() -> vulcano_legend
# 
ggsave(filename = "Beta_diversity_legend.jpeg",
path = "C:/Users/zuendj/Desktop/03_data R/wp1/follow_up/output_seq",
 width = 14,
 height = 17,
units = c("cm"))

63.5/17*7.5

```

